#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PATH=/usr/local/bin:$PATH
TMPDIR=${TMPDIR:-/tmp}

source $(dirname $0)/common

destination=${1}

if [ -z "${destination}" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload=$(mktemp ${TMPDIR}/artifactory-resource-request.XXXXXX)

cat > $payload <&0

api_key=$(jq -r '.source.api_key // ""' < ${payload})
repository_id=$(jq -r '.source.repository_id // ""' < ${payload})
group_id=$(jq -r '.source.group_id // ""' < ${payload})
artifact_id=$(jq -r '.source.artifact_id // ""' < ${payload})
host=$(jq -r '.source.host // ""' < ${payload})
version=$(jq -r '.version.ref // ""' < ${payload})
qualifiers_param=$(jq -r '.params // {}|.qualifiers // []|join(" ")' < ${payload})

is_valid 'api_key' "${api_key}"
is_valid 'repository_id' "${repository_id}"
is_valid 'group_id' "${group_id}"
is_valid 'artifact_id' "${artifact_id}"
is_valid 'host' "${host}"
is_valid 'version' "${version}"

host=$(strip_last_slash "${host}")
group_id_path=$(echo "${group_id}" | sed 's/\./\//g')

# Configure jfrog cli
jfrog rt config --url=$host --apikey=$api_key --interactive=false

# Default dowload function
if [ ${version} =~ "SNAPSHOT" ]; then
  artefact_search_path="${repository_id}/${group_id_path}/${artifact_id}/${version}/${artifact_id}-${version}-*.*"
else
  artefact_search_path="${repository_id}/${group_id_path}/${artifact_id}/${version}/${artifact_id}-${version}.*"
fi

jfrog rt dl "$artefact_search_path" "$destination/" --flat
# Download evidences
for qualifier in $qualifiers_param; do
  jfrog rt dl "${repository_id}/${group_id_path}/${artifact_id}/${version}/${artifact_id}-${version}-${qualifier}.*" "$destination/" --flat
done


if [ ! -z "$(ls -A $destination)" ]; then

  echo "${version}" > $destination/version

  # TODO add to metadat the list of item
  metadata_folder=$(folder_metadata "${payload}" "${destination}" "${version}")
  metadata_files=$(echo $(find ${destination} -type f -name "*" -not -name "version" -not -name "artifactory-resource-request*" -not -name "build" -not -name "_remote.repositories" -exec basename {} \; | jq -R -s -c 'split("\n")' | jq 'map(select(length > 0))') | jq '[.|to_entries[]|{name: "file_\(.key)", value}]')
  echo $(echo "\"${version}\"" | jq "{version: {ref: .}, metadata: $(echo ${metadata_folder} | jq ". + ${metadata_files}")}") >&3
  exit 0
else
  echo "Unable to retreive files in artifactory" >&2
  echo "Download path was: ${group_id_path}/${artifact_id}/${version}/${artifact_id}-${version}.*" >&2
  exit 1
fi